### ISSUE TITLE
Checkboxes not working on Table-tasks 

### ISSUE THREAD

**Issue by dragosct** [creativetimofficial/ct-paper-dashboard-pro#5]
Hi! For fixing this issue please go in the project to `examples/stats.html` page and search for `table-tasks` and inside of this table you must find the following lines of code: 
```html
<label class="checkbox">
         <input type="checkbox" value="" data-toggle="checkbox">
</label>
```
This code must be replaced everywhere with the following lines of code: 
```html
<div class="checkbox">													
    <input id="checkbox10" type="checkbox">															
    <label for="checkbox10"></label>	
</div>
```
The `id` of the checkboxes must be different for every checkbox.

Now you must go in `assets/css/paper-dashboard.css` and add the following lines of code at the bottom of the page:
```css
.table-tasks .table {
  margin-bottom: 0;
}

.table .checkbox {
  margin: 0;
}
.table .checkbox label:before, .table .checkbox label:after {
  margin-left: 0;
}
```
