### ISSUE TITLE
SCSS not compilable!

### ISSUE THREAD

**Issue by JHerwig** [creativetimofficial/ct-paper-dashboard-pro#51]
I installed sass globaly (`npm i -g sass`) and try `sass paper-dashboard.scss paper.css`

I got these errors:
- Error: expected ";".
- Error: Top-level selectors may not contain the parent selector "&".

From these files:
- 'paper/plugins/element-ui/plugin-tags';
- 'paper/plugins/element-ui/plugin-slidert '
- 'paper/plugins/element-ui/plugin-select'
- 'paper/plugins/element-ui/plugin-inputs'
- 'paper/plugins/element-ui/plugin-tables'
- paper/inputs'

I solved the first error myself. But the second error from `paper/plugins/element-ui/plugin-select` and `paper/inputs` not. Please fix this!

**Comment by groovemen** [comment]
Hello @JHerwig, 

Thank you for using our products, please let us know what product are you using. 

All the best, 
Stefan

**Comment by JHerwig** [comment]
I am using "Paper-Dashboard 2 Pro"  for Vue.js
I tried other Packages but none of your scss is compileable with sass.

**Comment by ChrisToxz** [comment]
`Error: Top-level selectors may not contain the parent selector "&"`
Same issue, I solved it to change:
```
@mixin placeholder() {
    &::-moz-placeholder {@content;} // Firefox
    &::-ms-input-placeholder {@content;} // Internet Explorer 10+
    &::-webkit-input-placeholder {@content;} // Safari and Chrome
}
```
to:
```
@mixin placeholder() {
    ::-moz-placeholder {@content;} // Firefox
    ::-ms-input-placeholder {@content;} // Internet Explorer 10+
    ::-webkit-input-placeholder {@content;} // Safari and Chrome
}

```

**Comment by dragosct** [comment]
Hi, @JHerwig! To fix that issue you put for example: 

```css
.select-#{$type}.el-select .el-input  {
    .el-input__suffix{
      display: flex;
      align-items: center;
    }
    &:hover{
      .el-input__icon,
      input {
        &::placeholder{
          color: white;
        }
        color: white;
      }
}
```

to 

```css
.select-#{$type}.el-select .el-input  {
    .el-input__suffix{
      display: flex;
      align-items: center;
    }
}

.select-#{$type}.el-select .el-input:hover{
      .el-input__icon,
      input,
      .el-input__icon::placeholder,
      input::placeholder {
        color: white;          
      }
}
```

These changes must be made over all the code with the sign & to avoid that error. 

Regards,
Dragos
