### ISSUE TITLE
Sidebar from left side! 

### ISSUE THREAD

**Issue by dragosct** [creativetimofficial/ct-paper-dashboard-pro#7]
Hi! If you want to have the sidebar on the left side please follow the next steps: 

1. Go in your project in `assets/sass/paper/_responsive.scss` and search for the `@media (max-width: $screen-md){ code here }` and inside of this media query please add the following code: 

```css
.menu-on-left{
        .sidebar{
            right: auto;
            left:0;
            @include transform-translate-x(-230px);
        }

        .nav-open &{
            .main-panel{
                @include transform-translate-x(230px);
            }

            .sidebar{
                @include transform-translate-x(0px);

                .sidebar-wrapper li.active > a:not([data-toggle="collapse"]):before,
                .off-canvas-sidebar & .sidebar-wrapper li.active > a:not([data-toggle="collapse"]):before{
                    border-right: 12px solid #cfcfca;
                    border-left: 0;
                    right: 0;
                    left: auto;
                }

                .sidebar-wrapper li.active > a:not([data-toggle="collapse"]):after,
                .off-canvas-sidebar & .sidebar-wrapper li.active > a:not([data-toggle="collapse"]):after{
                    border-right: 12px solid #f4f3ef;
                    right: -1px;
                    left: auto;
                    border-left: 0;
                }
            }
        }
    }
```

2. After you do this please compile you scss with [Koala](koala-app.com) and please be sure that your output path is `assets/css/paper-dashboard.css`.  

3. Now you must go in your html pages and add on the body tag the class `.menu-on-left`.

Regards,
Dragos
